#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : udisks2
Version  : 2.7.5
Release  : 4
URL      : https://github.com/storaged-project/udisks/archive/udisks-2.7.5.tar.gz
Source0  : https://github.com/storaged-project/udisks/archive/udisks-2.7.5.tar.gz
Summary  : Disk Manager
Group    : Development/Tools
License  : GPL-2.0+ LGPL-2.1+
Requires: udisks2-bin
Requires: udisks2-config
Requires: udisks2-data
Requires: udisks2-lib
Requires: udisks2-locales
Requires: udisks2-doc
Requires: libatasmart
Requires: libblockdev
Requires: libbytesize
Requires: libiscsi
Requires: libstoragemgmt
Requires: volume_key
BuildRequires : acl-dev
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : gnome-common-dev
BuildRequires : gobject-introspection-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : intltool
BuildRequires : intltool-dev
BuildRequires : libconfig-dev
BuildRequires : libiscsi-dev
BuildRequires : libstoragemgmt-dev
BuildRequires : libxslt-bin
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(blockdev)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gmodule-2.0)
BuildRequires : pkgconfig(gudev-1.0)
BuildRequires : pkgconfig(libatasmart)
BuildRequires : pkgconfig(libconfig)
BuildRequires : pkgconfig(libsystemd)
BuildRequires : pkgconfig(polkit-agent-1)
BuildRequires : pkgconfig(polkit-gobject-1)
Patch1: 0001-Add-support-for-a-stateless-configuration-file.patch

%description
The Udisks project provides a daemon, tools and libraries to access and
manipulate disks, storage devices and technologies.

%package bin
Summary: bin components for the udisks2 package.
Group: Binaries
Requires: udisks2-data
Requires: udisks2-config

%description bin
bin components for the udisks2 package.


%package config
Summary: config components for the udisks2 package.
Group: Default

%description config
config components for the udisks2 package.


%package data
Summary: data components for the udisks2 package.
Group: Data

%description data
data components for the udisks2 package.


%package dev
Summary: dev components for the udisks2 package.
Group: Development
Requires: udisks2-lib
Requires: udisks2-bin
Requires: udisks2-data
Provides: udisks2-devel

%description dev
dev components for the udisks2 package.


%package doc
Summary: doc components for the udisks2 package.
Group: Documentation

%description doc
doc components for the udisks2 package.


%package lib
Summary: lib components for the udisks2 package.
Group: Libraries
Requires: udisks2-data

%description lib
lib components for the udisks2 package.


%package locales
Summary: locales components for the udisks2 package.
Group: Default

%description locales
locales components for the udisks2 package.


%prep
%setup -q -n udisks-udisks-2.7.5
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1516733621
%autogen --disable-static --enable-bcache --enable-btrfs --enable-lsm --enable-lvm2 --enable-lvmcache --enable-zram
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1516733621
rm -rf %{buildroot}
%make_install
%find_lang udisks2
## make_install_append content
mkdir -p %{buildroot}/usr/share/dbus-1/system.d/
cp data/org.freedesktop.UDisks2.conf %{buildroot}/usr/share/dbus-1/system.d/
mkdir -p %{buildroot}/usr/lib/udev/rules.d/
cp data/80-udisks2.rules %{buildroot}/usr/lib/udev/rules.d/
install -D udisks/udisks2.conf %{buildroot}/usr/share/defaults/udisks/udisks2.conf
## make_install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/udisksctl
/usr/bin/umount.udisks2
/usr/libexec/udisks2/udisksd

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/system/clean-mount-point@.service
/usr/lib/systemd/system/udisks2.service
/usr/lib/systemd/system/zram-setup@.service
/usr/lib/udev/rules.d/80-udisks2.rules

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/UDisks-2.0.typelib
/usr/share/bash-completion/completions/udisksctl
/usr/share/dbus-1/system-services/org.freedesktop.UDisks2.service
/usr/share/dbus-1/system.d/org.freedesktop.UDisks2.conf
/usr/share/defaults/udisks/udisks2.conf
/usr/share/gir-1.0/*.gir
/usr/share/polkit-1/actions/org.freedesktop.UDisks2.bcache.policy
/usr/share/polkit-1/actions/org.freedesktop.UDisks2.btrfs.policy
/usr/share/polkit-1/actions/org.freedesktop.UDisks2.lsm.policy
/usr/share/polkit-1/actions/org.freedesktop.UDisks2.lvm2.policy
/usr/share/polkit-1/actions/org.freedesktop.UDisks2.policy
/usr/share/polkit-1/actions/org.freedesktop.UDisks2.zram.policy

%files dev
%defattr(-,root,root,-)
/usr/include/udisks2/udisks/udisks-generated.h
/usr/include/udisks2/udisks/udisks.h
/usr/include/udisks2/udisks/udisksclient.h
/usr/include/udisks2/udisks/udisksenums.h
/usr/include/udisks2/udisks/udisksenumtypes.h
/usr/include/udisks2/udisks/udiskserror.h
/usr/include/udisks2/udisks/udisksmoduleiface.h
/usr/include/udisks2/udisks/udisksmoduleifacetypes.h
/usr/include/udisks2/udisks/udisksmoduleobject.h
/usr/include/udisks2/udisks/udisksobjectinfo.h
/usr/include/udisks2/udisks/udiskstypes.h
/usr/include/udisks2/udisks/udisksversion.h
/usr/lib64/libudisks2.so
/usr/lib64/pkgconfig/udisks2.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
%doc /usr/share/man/man5/*
%doc /usr/share/man/man8/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libudisks2.so.0
/usr/lib64/libudisks2.so.0.0.0
/usr/lib64/udisks2/modules/libudisks2_bcache.so
/usr/lib64/udisks2/modules/libudisks2_btrfs.so
/usr/lib64/udisks2/modules/libudisks2_lsm.so
/usr/lib64/udisks2/modules/libudisks2_lvm2.so
/usr/lib64/udisks2/modules/libudisks2_zram.so

%files locales -f udisks2.lang
%defattr(-,root,root,-)

